# Generated by Django 3.2.25 on 2024-11-17 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(help_text='Unique identifier for the menu item.', primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Name of the menu item (max 50 characters).', max_length=50)),
                ('item_type', models.CharField(help_text="Type or category of the menu item (e.g., 'Drink', 'Main Course').", max_length=50)),
                ('menu_type', models.CharField(help_text="Type or category of the menu item (e.g., 'BreakFast','Lunch','Fullday').", max_length=50)),
                ('item_cost', models.DecimalField(decimal_places=2, help_text='Cost of the item in the format XX.XX (e.g., 12.50).', max_digits=6)),
                ('item_description', models.CharField(help_text='Brief description of the menu item (max 255 characters).', max_length=255)),
                ('is_allergic', models.BooleanField(default=False, help_text='Indicates if the item contains allergens (True/False).')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Indicates if the item is vegetarian (True/False).')),
                ('item_last_upd_ts', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (auto-updated).')),
                ('item_create_date', models.DateField(auto_now_add=True, help_text='Date when the item was created (auto-generated).')),
                ('item_upd_usr_id', models.ForeignKey(blank=True, help_text='ID of the user who last updated the item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
