# Generated by Django 3.2.25 on 2024-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, help_text='This will be True/False based on availability of item'),
        ),
    ]
