# Generated by Django 3.2.25 on 2024-11-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_upd_usr_email',
            field=models.EmailField(blank=True, help_text='Email of the user who created the item.', max_length=255, null=True),
        ),
    ]
