# Generated by Django 3.2.25 on 2024-11-19 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_menuitem_item_upd_usr_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted the item.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Audit',
                'verbose_name_plural': 'Menu Audits',
            },
        ),
    ]
