# Generated by Django 3.2.25 on 2024-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuaudit',
            name='deleted_by_usr_email',
            field=models.EmailField(blank=True, help_text='Email of the user who created the item.', max_length=255, null=True),
        ),
    ]
