# Generated by Django 3.2.25 on 2024-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuaudit_deleted_by_usr_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuaudit',
            old_name='deleted_by',
            new_name='deleted_by_usr_id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(help_text="Type or category of the menu item (e.g., 'BreakFast','Lunch','Full day').", max_length=50),
        ),
    ]
