# Generated by Django 3.2.25 on 2025-02-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0006_auto_20241119_0258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(help_text='Unique identifier for the order.', primary_key=True, serialize=False)),
                ('order_placed_ts', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was placed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order placed.', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='total_cost_of_the_order', max_digits=10)),
                ('order_last_upd_ts', models.DateTimeField(auto_now=True, help_text='Timestamp when the order is last updated.')),
                ('table_number', models.IntegerField(blank=True, help_text='Number of the table the order belongs to.', max_length=5, null=True)),
                ('order_origin', models.CharField(blank=True, choices=[('online', 'Online'), ('restaurant', 'Restaurant'), ('table', 'Table')], help_text='The origin of the order', max_length=20, null=True)),
                ('customer_id', models.ForeignKey(help_text='Customer who placed the order.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the menu item (max 50 characters).', max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, help_text='Price of the Menu Item.', max_digits=6)),
                ('item_total', models.DecimalField(decimal_places=2, help_text='item price * quantity', max_digits=10)),
                ('menu_item', models.ForeignKey(help_text='Menu item in the order.', on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('order', models.ForeignKey(help_text='Reference to the order.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
        ),
    ]
