# Generated by Django 3.2.25 on 2025-02-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20241119_0258'),
        ('orders', '0002_remove_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(default=1, help_text='Menu item in the order.', on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the order placed for the Menu item.'),
        ),
    ]
